spring:
  # 数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/sell?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    # 不返还对象中为空的字段
    default-property-inclusion: non_null
mybatis:
  # 配置 mapper 文件的目录
  mapper-locations: classpath:mapper/*Dao.xml
server:
  port: 8080
  servlet:
    context-path: /sell
logging:
  level:
    root: info
    com.lx.sell: debug